version: '3.9'

services:
  db:
    container_name: postgres_demo
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
       - vol_1:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    restart: always
#
volumes:
  vol_1:
    external: true