# Generated by Django 4.1.5 on 2023-01-24 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0007_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["date_create"],
                "verbose_name": "Создать пост",
                "verbose_name_plural": "Создать посты",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Не больше 5000 символов",
                max_length=5000,
                null=True,
                verbose_name="Контент",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_create",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="likes_post",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Не больше 256 символов",
                max_length=256,
                verbose_name="Название",
            ),
        ),
    ]
