# Generated by Django 4.1.5 on 2023-01-24 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0008_alter_post_options_post_is_published_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        help_text="Не больше 5000 символов",
                        max_length=5000,
                        verbose_name="О себе",
                    ),
                ),
                (
                    "profile_img",
                    models.ImageField(
                        default="blank-profile-picture.png",
                        upload_to="profile_images/%Y/%m/%D/",
                        verbose_name="Аватар",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Создать профиль",
                "verbose_name_plural": "Создать профили",
                "ordering": ["-author"],
            },
        ),
    ]
