# Generated by Django 4.1.5 on 2023-01-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="amount",
            field=models.IntegerField(verbose_name="AMOUNT"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=256, verbose_name="AUTHOR"),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="PRICE"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=256, verbose_name="TITLE"),
        ),
    ]
