# Generated by Django 4.1.5 on 2023-01-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_book_amount_alter_book_author_alter_book_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="AUTHOR")),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=256, verbose_name="FIRST_NAME"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=256, verbose_name="LAST_NAME"),
                ),
                ("phone", models.CharField(max_length=28, verbose_name="PHONE")),
                ("email", models.EmailField(max_length=254)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="DISCOUNT"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.client",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.author",
            ),
        ),
    ]
