# Generated by Django 4.1.5 on 2023-01-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_author_client_book_client_alter_book_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="client",
        ),
        migrations.AddField(
            model_name="book",
            name="client",
            field=models.ManyToManyField(null=True, to="store.client"),
        ),
    ]
