# Generated by Django 4.1.5 on 2023-01-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="client",
            field=models.ManyToManyField(to="store.client"),
        ),
    ]
