# Generated by Django 4.1.5 on 2023-01-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_book_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="anotation",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
